# Generated by Django 5.0.4 on 2024-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_film_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
