# Generated by Django 5.0.4 on 2024-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='earnings',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
